# Generated by Django 3.0.5 on 2020-09-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeMachines',
            fields=[
                ('code', models.CharField(max_length=7, primary_key=True)),
                ('product_type', models.CharField(max_length=20)),
                ('water_line_compatible', models.BooleanField(default=False)),
                ('model_type', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoffeePods',
            fields=[
                ('code', models.CharField(max_length=7, primary_key=True)),
                ('product_type', models.CharField(max_length=20)),
                ('coffee_flavor', models.CharField(max_length=15)),
                ('pack_size', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
